name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ascii Box
      id: ascii-box
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Ascii Box
        setup-command: javac AsciiBox.java
        command: java AsciiBox
        input: ''
        expected-output: |
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          AAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAA
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          AAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAA
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          AAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAA
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
          +++++++++++++++++++++++++
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Ascii Box2
      id: ascii-box2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Ascii Box2
        setup-command: javac AsciiBox2.java
        command: java AsciiBox2
        input: ''
        expected-output: |
          AAAAAAAAAAAAAAAAAAAAAAAAAAA
          +++++++++++++++++++++++++++
          +++                     +++
          +++                     +++
          +++                     +++
          +++                     +++
          +++     CompSci         +++
          +++                     +++
          +++                     +++
          +++                     +++
          +++                     +++
          AAAAAAAAAAAAAAAAAAAAAAAAAAA
          +++++++++++++++++++++++++++
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Input Test
      id: input-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Input Test
        setup-command: javac Input.java
        command: java Input
        input: |
          5
          6
          8
          9
          4
          10
          1
          2
        expected-output: |
          integer one = 5
          integer two = 6

          double one = 8.0
          double two = 9.0

          float one = 4.0
          float two = 10.0

          short one = 1
          short two = 2
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASCII-BOX_RESULTS: "${{steps.ascii-box.outputs.result}}"
        ASCII-BOX2_RESULTS: "${{steps.ascii-box2.outputs.result}}"
        INPUT-TEST_RESULTS: "${{steps.input-test.outputs.result}}"
      with:
        runners: ascii-box,ascii-box2,input-test
